### ISSUE TITLE
"Undefined" displayed to user until scores data persisted locally

### ISSUE THREAD

**Issue by jeffDevelops** [oakesrandall/project1#3]
Hey, David!

I noticed that you display "undefined" to the user for the first round of your game, which is great if the user is a programmer and understands what that means, but not so great for the lay user. Maybe instead, you could have an if statement saying, if the score stats are undefined, you could display: none the stats part of the interface. Or maybe you could come up with your own solution! 

Great job on your game!
Jeff

**Comment by oakesrandall** [comment]
Fixed by declaring initial variables outside of the function.

**Comment by oakesrandall** [comment]
Hahahahaha...just kidding.  That fixed it but caused a LOT more problems, which were super fun to track down.  Now it's fixed for reals.
