### ISSUE TITLE
UI idea: make reactive with media queries

### ISSUE THREAD

**Issue by samascher** [oakesrandall/project1#4]
hey david - loved your project. i loved the "old school" vibe of the fonts / colors you choose. this game would be awesome on a mobile device - something that would be especially useful and delightful to keep kids entertained (with headphones!!) 

can you try and work on the reactibility to get this to work on mobile?

**Comment by oakesrandall** [comment]
It now scrolls nicely down to a breakpoint specifically for mobile phones.  Thanks!
