### ISSUE TITLE
Consider a modal or some other win notification

### ISSUE THREAD

**Issue by jeffDevelops** [oakesrandall/project1#5]
Hey, David!

As a user, I never like getting alerts from my browser. They're great for getting feedback for when your stuff works as a developer, but is there any other way you could alert your user that flows with the interface you already have? Maybe a modal, or a notification in a new div where you already have some whitespace on your interface?

Great job on your game!
Jeff

**Comment by oakesrandall** [comment]
Good idea. Done.
